name: Sync Gitea Page Branch to GitHub

on:
  # Trigger on manual dispatch
  workflow_dispatch:

  # Trigger on push to page branch
  push:
    branches:
      - page

  # Schedule to run weekly
  schedule:
    - cron: "0 3 * * 6" # Run weekly at 03:00 on Saturday

jobs:
  sync-gitea-to-github:
    runs-on: docker
    container:
      image: node:18
    permissions:
      contents: read

    steps:
      - name: Checkout page branch
        uses: actions/checkout@v4
        with:
          ref: page
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "psygreg@pm.me"
          git config --local user.name "psygreg"

      - name: Push page branch to GitHub main
        run: |
          git push https://x-access-token:${{ secrets.GHTOKEN }}@github.com/psygreg/linuxtoys-site.git page:main --force-with-lease
