import json
import os

# Directory containing the language files
lang_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "p3/libs/lang/")

# Translations dictionary: key -> {lang_code: translation}
translations = {
    "ubuntuv3": {
        "am": "የx86-64v3 ጥቅሎችን አንቃ",
        "ar": "تمكين حزم x86-64v3",
        "az": "x86-64v3 paketlərini aktivləşdir",
        "bg": "Активиране на пакетите x86-64v3",
        "bn": "x86-64v3 প্যাকেজ সক্রিয় করুন",
        "bs": "Omogući x86-64v3 pakete",
        "cs": "Povolit balíčky x86-64v3",
        "da": "Aktivér x86-64v3-pakker",
        "de": "x86-64v3-Pakete aktivieren",
        "el": "Ενεργοποίηση πακέτων x86-64v3",
        "es": "Habilitar paquetes x86-64v3",
        "et": "Luba x86-64v3 paketid",
        "fa": "فعال‌سازی بسته‌های x86-64v3",
        "fi": "Ota käyttöön x86-64v3-paketit",
        "fr": "Activer les paquets x86-64v3",
        "ga": "Cumasaigh pacáistí x86-64v3",
        "he": "הפעל חבילות x86-64v3",
        "hi": "x86-64v3 पैकेज सक्षम करें",
        "hr": "Omogući x86-64v3 pakete",
        "hu": "x86-64v3 csomagok engedélyezése",
        "hy": "Միացնել x86-64v3 փաթեթները",
        "id": "Aktifkan paket x86-64v3",
        "is": "Virkja x86-64v3 pakka",
        "it": "Abilita i pacchetti x86-64v3",
        "ja": "x86-64v3 パッケージを有効化",
        "ka": "x86-64v3 პაკეტების ჩართვა",
        "km": "បើកកញ្ចប់ x86-64v3",
        "ko": "x86-64v3 패키지 활성화",
        "lo": "ເປີດໃຊ້ແພັກເກດ x86-64v3",
        "lt": "Įjungti x86-64v3 paketus",
        "lv": "Iespējot x86-64v3 pakotnes",
        "mn": "x86-64v3 багцуудыг идэвхжүүлэх",
        "ms": "Dayakan pakej x86-64v3",
        "my": "x86-64v3 ပက်ကေ့ဂျ်များကို ဖွင့်ပါ",
        "nb": "Aktiver x86-64v3-pakker",
        "ne": "x86-64v3 प्याकेज सक्षम गर्नुहोस्",
        "nl": "x86-64v3-pakketten inschakelen",
        "pl": "Włącz pakiety x86-64v3",
        "pt": "Ativar pacotes x86-64v3",
        "ro": "Activează pachetele x86-64v3",
        "ru": "Включить пакеты x86-64v3",
        "sk": "Povoliť balíky x86-64v3",
        "sl": "Omogoči pakete x86-64v3",
        "sq": "Aktivizo paketat x86-64v3",
        "sr": "Омогући x86-64v3 пакете",
        "sv": "Aktivera x86-64v3-paket",
        "sw": "Washa vifurushi vya x86-64v3",
        "ta": "x86-64v3 தொகுப்புகளை இயக்கு",
        "tg": "Фаъол кардани бастаҳои x86-64v3",
        "th": "เปิดใช้งานแพ็กเกจ x86-64v3",
        "tl": "Paganahin ang mga paketeng x86-64v3",
        "tr": "x86-64v3 paketlerini etkinleştir",
        "uk": "Увімкнути пакунки x86-64v3",
        "ur": "x86-64v3 پیکیجز فعال کریں",
        "uz": "x86-64v3 paketlarini yoqish",
        "vi": "Bật gói x86-64v3",
        "zh": "启用 x86-64v3 软件包"
    },
    "ubuntuv3_desc": {
        "am": "በUbuntu ላይ ለx86-64v3 ፕሮሰሰሮች የተሻሻሉ ጥቅሎችን እንዲመረጡ ያዘጋጃል፣ ይህም ትንሽ የአፈጻጸም መሻሻል ሊያመጣ ይችላል።",
        "ar": "يضبط النظام لتفضيل الحزم المحسّنة لمعالجات x86-64v3 على Ubuntu، مما قد يوفر تحسينات طفيفة في الأداء.",
        "az": "Ubuntu-da x86-64v3 prosessorları üçün optimallaşdırılmış paketlərə üstünlük verir ki, bu da kiçik performans artımı təmin edə bilər.",
        "bg": "Настройва Ubuntu да предпочита оптимизирани пакети за процесори x86-64v3, което може да доведе до малки подобрения в производителността.",
        "bn": "Ubuntu-তে x86-64v3 প্রসেসরের জন্য অপ্টিমাইজ করা প্যাকেজগুলিকে অগ্রাধিকার দেয়, যা সামান্য কর্মক্ষমতা বৃদ্ধি করতে পারে।",
        "bs": "Postavlja Ubuntu da daje prednost optimiziranim paketima za x86-64v3 procesore, što može donijeti mala poboljšanja performansi.",
        "cs": "Nastaví Ubuntu tak, aby upřednostňoval optimalizované balíčky pro procesory x86-64v3, což může přinést malé zlepšení výkonu.",
        "da": "Indstiller Ubuntu til at foretrække optimerede pakker til x86-64v3-processorer, hvilket kan give en mindre ydelsesforbedring.",
        "de": "Richtet Ubuntu so ein, dass optimierte Pakete für x86-64v3-Prozessoren bevorzugt werden, was zu kleinen Leistungsverbesserungen führen kann.",
        "el": "Ρυθμίζει το Ubuntu ώστε να προτιμά βελτιστοποιημένα πακέτα για επεξεργαστές x86-64v3, κάτι που μπορεί να προσφέρει μικρές βελτιώσεις στην απόδοση.",
        "es": "Configura Ubuntu para dar prioridad a los paquetes optimizados para procesadores x86-64v3, lo que puede aportar pequeñas mejoras de rendimiento.",
        "et": "Seadistab Ubuntu eelistama x86-64v3 protsessoritele optimeeritud pakette, mis võivad pakkuda väikest jõudluse paranemist.",
        "fa": "اوبونتو را طوری تنظیم می‌کند که بسته‌های بهینه‌شده برای پردازنده‌های x86-64v3 را ترجیح دهد؛ این کار ممکن است بهبود اندکی در عملکرد ایجاد کند.",
        "fi": "Asettaa Ubuntun suosimaan x86-64v3-suorittimille optimoituja pakette, mikä voi tuoda pieniä suorituskykyparannuksia.",
        "fr": "Configure Ubuntu pour privilégier les paquets optimisés pour les processeurs x86-64v3, ce qui peut apporter de légères améliorations de performances.",
        "ga": "Cumraíonn sé Ubuntu chun tosaíocht a thabhairt do phacáistí optamaithe do phróiseálaithe x86-64v3, rud a d'fhéadfadh feabhsuithe beaga feidhmíochta a thabhairt.",
        "he": "מגדיר את Ubuntu להעדיף חבילות המותאמות למעבדי x86-64v3, מה שעשוי להביא לשיפור קטן בביצועים.",
        "hi": "Ubuntu को x86-64v3 प्रोसेसरों के लिए अनुकूलित पैकेजों को प्राथमिकता देने हेतु कॉन्फ़िगर करता है, जिससे प्रदर्शन में थोड़ा सुधार हो सकता है।",
        "hr": "Postavlja Ubuntu da daje prednost optimiziranim paketima za x86-64v3 procesore, što može donijeti manja poboljšanja performansi.",
        "hu": "Úgy állítja be az Ubuntut, hogy előnyben részesítse az x86-64v3 processzorokra optimalizált csomagokat, ami kisebb teljesítménynövekedést eredményezhet.",
        "hy": "Կարգավորում է Ubuntu-ն, որպեսզի նախընտրի x86-64v3 պրոցեսորների համար օպտիմիզացված փաթեթները, ինչը կարող է փոքր արդյունավետության բարելավում ապահովել։",
        "id": "Mengatur Ubuntu agar mengutamakan paket yang dioptimalkan untuk prosesor x86-64v3, yang dapat memberikan sedikit peningkatan kinerja.",
        "is": "Stillir Ubuntu til að forgangsraða bjartsýnum pökkum fyrir x86-64v3 örgjörva, sem getur skilað lítilsháttar afkastabótum.",
        "it": "Configura Ubuntu per dare priorità ai pacchetti ottimizzati per processori x86-64v3, con possibili piccoli miglioramenti delle prestazioni.",
        "ja": "Ubuntuでx86-64v3プロセッサ向けに最適化されたパッケージを優先するよう設定し、わずかな性能向上が期待できます。",
        "ka": "აყენებს Ubuntu-ს ისე, რომ უპირატესობა მიანიჭოს x86-64v3 პროცესორებისთვის ოპტიმიზებულ პაკეტებს, რაც შეიძლება მცირე წარმადობის გაუმჯობესებას უზრუნველყოფდეს.",
        "km": "កំណត់ Ubuntu ឱ្យផ្តល់អាទិភាពដល់កញ្ចប់ដែលបានបង្កើនប្រសិទ្ធភាពសម្រាប់ប្រព័ន្ធដំណើរការ x86-64v3 ដែលអាចផ្តល់ការកែលម្អប្រសិទ្ធភាពបន្តិចបន្តួច។",
        "ko": "Ubuntu에서 x86-64v3 프로세서에 최적화된 패키지를 우선 사용하도록 설정하여 약간의 성능 향상을 얻을 수 있습니다.",
        "lo": "ຕັ້ງຄ່າ Ubuntu ໃຫ້ເລືອກໃຊ້ແພັກເກດທີ່ປັບແຕ່ງສຳລັບໂປຣເຊສເຊີ x86-64v3 ກ່ອນ ເຊິ່ງອາດຈະເພີ່ມປະສິດທິພາບໄດ້ເລັກນ້ອຍ.",
        "lt": "Nustato Ubuntu teikti pirmenybę x86-64v3 procesoriams optimizuotiems paketams, kurie gali šiek tiek pagerinti našumą.",
        "lv": "Iestata Ubuntu dot priekšroku x86-64v3 procesoriem optimizētām pakotnēm, kas var sniegt nelielus veiktspējas uzlabojumus.",
        "mn": "Ubuntu-г x86-64v3 процессорт зориулан оновчлогдсон багцуудыг илүүд үзэхээр тохируулдаг бөгөөд энэ нь бага зэргийн гүйцэтгэлийн сайжруулалт авчирч болзошгүй.",
        "ms": "Menetapkan Ubuntu supaya mengutamakan pakej yang dioptimumkan untuk pemproses x86-64v3, yang boleh memberikan sedikit peningkatan prestasi.",
        "my": "Ubuntu တွင် x86-64v3 ပရိုဆက်ဆာများအတွက် အကောင်းဆုံးပြင်ဆင်ထားသော ပက်ကေ့ဂျ်များကို ဦးစားပေးအသုံးပြုရန် သတ်မှတ်ပေးပြီး စွမ်းဆောင်ရည် အနည်းငယ်တိုးတက်လာနိုင်သည်။",
        "nb": "Setter opp Ubuntu til å foretrekke optimaliserte pakker for x86-64v3-prosessorer, noe som kan gi en liten ytelsesforbedring.",
        "ne": "Ubuntu लाई x86-64v3 प्रोसेसरका लागि अनुकूलित प्याकेजहरू प्राथमिकता दिन सेट गर्छ, जसले सानो प्रदर्शन सुधार ल्याउन सक्छ।",
        "nl": "Stelt Ubuntu in om geoptimaliseerde pakketten voor x86-64v3-processors te verkiezen, wat kleine prestatieverbeteringen kan opleveren.",
        "pl": "Konfiguruje Ubuntu tak, aby preferował pakiety zoptymalizowane dla procesorów x86-64v3, co może przynieść niewielką poprawę wydajności.",
        "pt": "Configura o Ubuntu para dar preferência a pacotes otimizados para processadores x86-64v3, o que pode trazer pequenos ganhos de desempenho.",
        "ro": "Configurează Ubuntu să prefere pachetele optimizate pentru procesoarele x86-64v3, ceea ce poate aduce mici îmbunătățiri de performanță.",
        "ru": "Настраивает Ubuntu на использование оптимизированных пакетов для процессоров x86-64v3, что может дать небольшое повышение производительности.",
        "sk": "Nastaví Ubuntu tak, aby uprednostňoval optimalizované balíky pre procesory x86-64v3, čo môže priniesť malé zvýšenie výkonu.",
        "sl": "Nastavi Ubuntu tako, da daje prednost paketom, optimiziranim za procesorje x86-64v3, kar lahko prinese manjše izboljšanje zmogljivosti.",
        "sq": "Konfiguron Ubuntu-n që të preferojë paketat e optimizuara për procesorët x86-64v3, gjë që mund të sjellë përmirësime të vogla në performancë.",
        "sr": "Подешава Ubuntu да даје предност пакетима оптимизованим за x86-64v3 процесоре, што може донети мања побољшања перформанси.",
        "sv": "Ställer in Ubuntu att föredra optimerade paket för x86-64v3-processorer, vilket kan ge mindre prestandaförbättringar.",
        "sw": "Husanidi Ubuntu ili kupendelea vifurushi vilivyoboreshwa kwa vichakataji vya x86-64v3, jambo ambalo linaweza kuleta maboresho madogo ya utendaji.",
        "ta": "Ubuntu-வில் x86-64v3 செயலிகளுக்காக மேம்படுத்தப்பட்ட தொகுப்புகளுக்கு முன்னுரிமை அளிக்க அமைக்கிறது; இது சிறிய செயல்திறன் மேம்பாடுகளை வழங்கலாம்.",
        "tg": "Ubuntu-ро тавре танзим мекунад, ки бастаҳои барои протсессорҳои x86-64v3 оптимизатсияшударо афзал донад, ки метавонад беҳбудиҳои хурди самаранокиро ба бор орад.",
        "th": "กำหนดค่า Ubuntu ให้เลือกใช้แพ็กเกจที่ปรับแต่งมาสำหรับโปรเซสเซอร์ x86-64v3 เป็นลำดับแรก ซึ่งอาจช่วยเพิ่มประสิทธิภาพได้เล็กน้อย",
        "tl": "Itinatakda ang Ubuntu na unahin ang mga paketeng na-optimize para sa mga x86-64v3 processor, na maaaring magbigay ng kaunting pagbuti sa pagganap.",
        "tr": "Ubuntu'yu x86-64v3 işlemciler için optimize edilmiş paketleri tercih edecek şekilde yapılandırır; bu da küçük performans artışları sağlayabilir.",
        "uk": "Налаштовує Ubuntu на використання оптимізованих пакунків для процесорів x86-64v3, що може дати невелике підвищення продуктивності.",
        "ur": "Ubuntu کو اس طرح ترتیب دیتا ہے کہ وہ x86-64v3 پروسیسرز کے لیے بہتر بنائے گئے پیکیجز کو ترجیح دے، جس سے کارکردگی میں معمولی بہتری آ سکتی ہے۔",
        "uz": "Ubuntu'ni x86-64v3 protsessorlari uchun optimallashtirilgan paketlarni afzal ko‘radigan qilib sozlaydi, bu esa unumdorlikni biroz oshirishi mumkin.",
        "vi": "Thiết lập Ubuntu ưu tiên các gói được tối ưu hóa cho bộ xử lý x86-64v3, có thể mang lại một số cải thiện nhỏ về hiệu năng.",
        "zh": "将 Ubuntu 配置为优先使用针对 x86-64v3 处理器优化的软件包，可能带来一定的性能提升。"
    },
}

# Skip 'en' since it's already added
for key, lang_translations in translations.items():
    for lang, translation in lang_translations.items():
        file_path = os.path.join(lang_dir, f"{lang}.json")
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data[key] = translation
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Added {key} to {lang}.json")
        else:
            print(f"File {file_path} does not exist")
