import json
import os

# Directory containing the language files
lang_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "p3/libs/lang/")

# Translations dictionary: key -> {lang_code: translation}
translations = {
    "amdgpu_desc": {
        "am": "በUbuntu LTS እና Red Hat Enterprise Linux ላይ የቅርብ ጊዜዎቹን የAMD Radeon ግራፊክስ ነጂዎች ይጫኑ።",
        "ar": "ثبّت أحدث برامج تشغيل بطاقات AMD Radeon الرسومية على Ubuntu LTS وRed Hat Enterprise Linux.",
        "az": "Ubuntu LTS və Red Hat Enterprise Linux sistemlərində ən son AMD Radeon qrafika sürücülərini quraşdırın.",
        "bg": "Инсталирайте най-новите графични драйвери за AMD Radeon в Ubuntu LTS и Red Hat Enterprise Linux.",
        "bn": "Ubuntu LTS এবং Red Hat Enterprise Linux-এ সর্বশেষ AMD Radeon গ্রাফিক্স ড্রাইভার ইনস্টল করুন।",
        "bs": "Instalirajte najnovije AMD Radeon grafičke upravljačke programe na Ubuntu LTS i Red Hat Enterprise Linux.",
        "cs": "Nainstalujte nejnovější grafické ovladače AMD Radeon v Ubuntu LTS a Red Hat Enterprise Linux.",
        "da": "Installér de nyeste AMD Radeon-grafikdrivere på Ubuntu LTS og Red Hat Enterprise Linux.",
        "de": "Installieren Sie die neuesten AMD-Radeon-Grafiktreiber unter Ubuntu LTS und Red Hat Enterprise Linux.",
        "el": "Εγκαταστήστε τα πιο πρόσφατα προγράμματα οδήγησης γραφικών AMD Radeon στο Ubuntu LTS και το Red Hat Enterprise Linux.",
        "es": "Instala los controladores gráficos AMD Radeon más recientes en Ubuntu LTS y Red Hat Enterprise Linux.",
        "et": "Paigaldage uusimad AMD Radeoni graafikadraiverid Ubuntu LTS-i ja Red Hat Enterprise Linuxi.",
        "fa": "جدیدترین درایورهای گرافیکی AMD Radeon را روی Ubuntu LTS و Red Hat Enterprise Linux نصب کنید.",
        "fi": "Asenna uusimmat AMD Radeon -näytönohjaimet Ubuntu LTS:ään ja Red Hat Enterprise Linuxiin.",
        "fr": "Installez les derniers pilotes graphiques AMD Radeon sur Ubuntu LTS et Red Hat Enterprise Linux.",
        "ga": "Suiteáil na tiománaithe grafaice AMD Radeon is déanaí ar Ubuntu LTS agus Red Hat Enterprise Linux.",
        "he": "התקינו את מנהלי ההתקן הגרפיים העדכניים ביותר של AMD Radeon ב-Ubuntu LTS וב-Red Hat Enterprise Linux.",
        "hi": "Ubuntu LTS और Red Hat Enterprise Linux पर नवीनतम AMD Radeon ग्राफ़िक्स ड्राइवर इंस्टॉल करें।",
        "hr": "Instalirajte najnovije AMD Radeon grafičke upravljačke programe na Ubuntu LTS i Red Hat Enterprise Linux.",
        "hu": "Telepítse a legújabb AMD Radeon grafikus illesztőprogramokat Ubuntu LTS és Red Hat Enterprise Linux rendszerekre.",
        "hy": "Տեղադրեք AMD Radeon-ի գրաֆիկական վերջին դրայվերները Ubuntu LTS և Red Hat Enterprise Linux համակարգերում։",
        "id": "Instal driver grafis AMD Radeon terbaru di Ubuntu LTS dan Red Hat Enterprise Linux.",
        "is": "Settu upp nýjustu AMD Radeon-skjákortareklana á Ubuntu LTS og Red Hat Enterprise Linux.",
        "it": "Installa i driver grafici AMD Radeon più recenti su Ubuntu LTS e Red Hat Enterprise Linux.",
        "ja": "Ubuntu LTSおよびRed Hat Enterprise Linuxに最新のAMD Radeonグラフィックスドライバーをインストールします。",
        "ka": "დააყენეთ AMD Radeon-ის უახლესი გრაფიკული დრაივერები Ubuntu LTS-სა და Red Hat Enterprise Linux-ზე.",
        "km": "ដំឡើងកម្មវិធីបញ្ជាក្រាហ្វិក AMD Radeon ជំនាន់ចុងក្រោយនៅលើ Ubuntu LTS និង Red Hat Enterprise Linux។",
        "ko": "Ubuntu LTS 및 Red Hat Enterprise Linux에 최신 AMD Radeon 그래픽 드라이버를 설치합니다.",
        "lo": "ຕິດຕັ້ງໄດຣເວີກຣາຟິກ AMD Radeon ລ່າສຸດໃນ Ubuntu LTS ແລະ Red Hat Enterprise Linux.",
        "lt": "Įdiekite naujausias AMD Radeon grafikos tvarkykles Ubuntu LTS ir Red Hat Enterprise Linux sistemose.",
        "lv": "Instalējiet jaunākos AMD Radeon grafikas draiverus Ubuntu LTS un Red Hat Enterprise Linux sistēmās.",
        "mn": "Ubuntu LTS болон Red Hat Enterprise Linux дээр хамгийн сүүлийн үеийн AMD Radeon график драйверуудыг суулгана.",
        "ms": "Pasang pemacu grafik AMD Radeon terkini pada Ubuntu LTS dan Red Hat Enterprise Linux.",
        "my": "Ubuntu LTS နှင့် Red Hat Enterprise Linux တွင် နောက်ဆုံးပေါ် AMD Radeon ဂရပ်ဖစ်ဒရိုင်ဘာများကို ထည့်သွင်းပါ။",
        "nb": "Installer de nyeste AMD Radeon-grafikkdriverne på Ubuntu LTS og Red Hat Enterprise Linux.",
        "ne": "Ubuntu LTS र Red Hat Enterprise Linux मा नवीनतम AMD Radeon ग्राफिक्स ड्राइभरहरू स्थापना गर्नुहोस्।",
        "nl": "Installeer de nieuwste AMD Radeon-grafische stuurprogramma's op Ubuntu LTS en Red Hat Enterprise Linux.",
        "pl": "Zainstaluj najnowsze sterowniki graficzne AMD Radeon w systemach Ubuntu LTS i Red Hat Enterprise Linux.",
        "pt": "Instale os drivers gráficos AMD Radeon mais recentes no Ubuntu LTS e no Red Hat Enterprise Linux.",
        "ro": "Instalați cele mai recente drivere grafice AMD Radeon pe Ubuntu LTS și Red Hat Enterprise Linux.",
        "ru": "Установите новейшие графические драйверы AMD Radeon в Ubuntu LTS и Red Hat Enterprise Linux.",
        "sk": "Nainštalujte najnovšie grafické ovládače AMD Radeon v systémoch Ubuntu LTS a Red Hat Enterprise Linux.",
        "sl": "Namestite najnovejše grafične gonilnike AMD Radeon v Ubuntu LTS in Red Hat Enterprise Linux.",
        "sq": "Instaloni drejtuesit më të fundit grafikë AMD Radeon në Ubuntu LTS dhe Red Hat Enterprise Linux.",
        "sr": "Инсталирајте најновије AMD Radeon графичке управљачке програме на Ubuntu LTS и Red Hat Enterprise Linux.",
        "sv": "Installera de senaste AMD Radeon-grafikdrivrutinerna på Ubuntu LTS och Red Hat Enterprise Linux.",
        "sw": "Sakinisha viendeshi vya hivi karibuni vya michoro ya AMD Radeon kwenye Ubuntu LTS na Red Hat Enterprise Linux.",
        "ta": "Ubuntu LTS மற்றும் Red Hat Enterprise Linux-இல் சமீபத்திய AMD Radeon வரைகலை இயக்கிகளை நிறுவுங்கள்.",
        "tg": "Драйверҳои навтарини графикии AMD Radeon-ро дар Ubuntu LTS ва Red Hat Enterprise Linux насб кунед.",
        "th": "ติดตั้งไดรเวอร์กราฟิก AMD Radeon เวอร์ชันล่าสุดบน Ubuntu LTS และ Red Hat Enterprise Linux",
        "tl": "I-install ang pinakabagong AMD Radeon graphics driver sa Ubuntu LTS at Red Hat Enterprise Linux.",
        "tr": "Ubuntu LTS ve Red Hat Enterprise Linux üzerine en yeni AMD Radeon grafik sürücülerini yükleyin.",
        "uk": "Установіть найновіші графічні драйвери AMD Radeon в Ubuntu LTS і Red Hat Enterprise Linux.",
        "ur": "Ubuntu LTS اور Red Hat Enterprise Linux پر جدید ترین AMD Radeon گرافکس ڈرائیورز انسٹال کریں۔",
        "uz": "Ubuntu LTS va Red Hat Enterprise Linux tizimlariga eng so‘nggi AMD Radeon grafik drayverlarini o‘rnating.",
        "vi": "Cài đặt trình điều khiển đồ họa AMD Radeon mới nhất trên Ubuntu LTS và Red Hat Enterprise Linux.",
        "zh": "在 Ubuntu LTS 和 Red Hat Enterprise Linux 上安装最新的 AMD Radeon 显卡驱动程序。"
    },
    "theming_desc": {
        "am": "የስርዓትዎን እና የመተግበሪያዎችዎን ገጽታ እንደፍላጎትዎ ለማስተካከል የሚረዱ መሳሪያዎች።",
        "ar": "أدوات تساعدك على تخصيص مظهر نظامك وتطبيقاتك بما يناسب ذوقك.",
        "az": "Sisteminizin və tətbiqlərinizin görünüşünü zövqünüzə uyğunlaşdırmağa kömək edən alətlər.",
        "bg": "Инструменти, които ви помагат да настроите външния вид на системата и приложенията според предпочитанията си.",
        "bn": "আপনার পছন্দ অনুযায়ী সিস্টেম ও অ্যাপ্লিকেশনগুলোর চেহারা সাজাতে সহায়ক সরঞ্জাম।",
        "bs": "Alati koji vam pomažu da prilagodite izgled sistema i aplikacija prema svom ukusu.",
        "cs": "Nástroje, které vám pomohou přizpůsobit vzhled systému i aplikací podle vašich představ.",
        "da": "Værktøjer, der hjælper dig med at tilpasse systemets og programmernes udseende efter din smag.",
        "de": "Werkzeuge, mit denen Sie das Erscheinungsbild Ihres Systems und Ihrer Anwendungen nach Ihren Wünschen anpassen können.",
        "el": "Εργαλεία που σας βοηθούν να προσαρμόσετε την εμφάνιση του συστήματος και των εφαρμογών σας όπως σας αρέσει.",
        "es": "Herramientas para adaptar la apariencia de tu sistema y aplicaciones a tu gusto.",
        "et": "Tööriistad süsteemi ja rakenduste välimuse kohandamiseks vastavalt teie eelistustele.",
        "fa": "ابزارهایی برای تنظیم ظاهر سیستم و برنامه‌ها مطابق سلیقه شما.",
        "fi": "Työkaluja järjestelmän ja sovellusten ulkoasun mukauttamiseen mieleiseksesi.",
        "fr": "Des outils pour personnaliser l'apparence de votre système et de vos applications selon vos préférences.",
        "ga": "Uirlisí chun cuma do chórais agus do chuid feidhmchlár a chur in oiriúint do do rogha.",
        "he": "כלים שיעזרו לך להתאים את מראה המערכת והיישומים לטעמך.",
        "hi": "ऐसे उपकरण जो आपके सिस्टम और अनुप्रयोगों का रूप-रंग आपकी पसंद के अनुसार ढालने में मदद करते हैं।",
        "hr": "Alati koji vam pomažu prilagoditi izgled sustava i aplikacija prema vašim željama.",
        "hu": "Eszközök a rendszer és az alkalmazások megjelenésének ízlés szerinti testreszabásához.",
        "hy": "Գործիքներ, որոնք օգնում են հարմարեցնել համակարգի և ծրագրերի տեսքը ձեր նախասիրություններին համապատասխան։",
        "id": "Alat untuk membantu menyesuaikan tampilan sistem dan aplikasi sesuai selera Anda.",
        "is": "Verkfæri til að laga útlit kerfisins og forrita að þínum smekk.",
        "it": "Strumenti per personalizzare l'aspetto del sistema e delle applicazioni secondo le tue preferenze.",
        "ja": "システムやアプリケーションの外観を好みに合わせて調整するためのツールです。",
        "ka": "ინსტრუმენტები, რომლებიც დაგეხმარებათ თქვენი სისტემისა და პროგრამების იერსახის თქვენს გემოვნებაზე მორგებაში.",
        "km": "ឧបករណ៍សម្រាប់ជួយកែសម្រួលរូបរាងរបស់ប្រព័ន្ធ និងកម្មវិធីឱ្យសមនឹងចំណង់ចំណូលចិត្តរបស់អ្នក។",
        "ko": "시스템과 애플리케이션의 모양을 원하는 대로 꾸밀 수 있도록 도와주는 도구입니다.",
        "lo": "ເຄື່ອງມືທີ່ຊ່ວຍປັບແຕ່ງຮູບລັກຂອງລະບົບ ແລະ ແອັບໃຫ້ຕາມຄວາມມັກຂອງທ່ານ.",
        "lt": "Įrankiai, padedantys pritaikyti sistemos ir programų išvaizdą pagal savo skonį.",
        "lv": "Rīki sistēmas un lietotņu izskata pielāgošanai pēc jūsu vēlmēm.",
        "mn": "Систем болон програмуудын харагдах байдлыг өөрийн хүссэнээр тохируулахад туслах хэрэгслүүд.",
        "ms": "Alat untuk membantu anda melaraskan penampilan sistem dan aplikasi mengikut cita rasa anda.",
        "my": "သင့်စိတ်ကြိုက် စနစ်နှင့် အက်ပ်များ၏ အသွင်အပြင်ကို ပြင်ဆင်နိုင်ရန် ကူညီပေးသော ကိရိယာများ။",
        "nb": "Verktøy som hjelper deg med å tilpasse utseendet til systemet og programmene slik du ønsker.",
        "ne": "तपाईंको रुचिअनुसार प्रणाली र अनुप्रयोगहरूको स्वरूप मिलाउन मद्दत गर्ने उपकरणहरू।",
        "nl": "Hulpmiddelen om het uiterlijk van je systeem en toepassingen naar wens aan te passen.",
        "pl": "Narzędzia pomagające dostosować wygląd systemu i aplikacji do własnych upodobań.",
        "pt": "Ferramentas para ajudar a ajustar a aparência do seu sistema e aplicativos ao seu gosto.",
        "ro": "Instrumente care vă ajută să adaptați aspectul sistemului și al aplicațiilor după preferințele dumneavoastră.",
        "ru": "Инструменты для настройки внешнего вида системы и приложений по вашему вкусу.",
        "sk": "Nástroje na prispôsobenie vzhľadu systému a aplikácií podľa vašich predstáv.",
        "sl": "Orodja za prilagajanje videza sistema in programov po vaših željah.",
        "sq": "Mjete për të përshtatur pamjen e sistemit dhe aplikacioneve sipas dëshirës suaj.",
        "sr": "Алати који вам помажу да прилагодите изглед система и апликација по свом укусу.",
        "sv": "Verktyg som hjälper dig att anpassa systemets och programmens utseende efter din smak.",
        "sw": "Zana zinazokusaidia kurekebisha mwonekano wa mfumo na programu zako upendavyo.",
        "ta": "உங்கள் விருப்பத்திற்கு ஏற்ப கணினி மற்றும் பயன்பாடுகளின் தோற்றத்தை மாற்ற உதவும் கருவிகள்.",
        "tg": "Асбобҳое, ки ба шумо барои мутобиқ кардани намуди система ва барномаҳо мувофиқи завқи худ кӯмак мекунанд.",
        "th": "เครื่องมือที่ช่วยให้คุณปรับแต่งรูปลักษณ์ของระบบและแอปพลิเคชันตามที่คุณต้องการ",
        "tl": "Mga kasangkapang tutulong sa iyong iangkop ang hitsura ng iyong system at mga application ayon sa gusto mo.",
        "tr": "Sisteminizin ve uygulamalarınızın görünümünü istediğiniz gibi ayarlamanıza yardımcı olan araçlar.",
        "uk": "Інструменти, які допоможуть налаштувати вигляд системи та програм на свій смак.",
        "ur": "ایسے اوزار جو آپ کے نظام اور ایپلی کیشنز کی ظاہری شکل کو آپ کی پسند کے مطابق ڈھالنے میں مدد دیتے ہیں۔",
        "uz": "Tizim va ilovalaringizning ko‘rinishini didingizga moslashtirishga yordam beruvchi vositalar.",
        "vi": "Các công cụ giúp bạn tinh chỉnh giao diện của hệ thống và ứng dụng theo ý thích.",
        "zh": "帮助您按照自己的喜好调整系统和应用程序外观的工具。"
    },
}

# Skip 'en' since it's already added
for key, lang_translations in translations.items():
    for lang, translation in lang_translations.items():
        file_path = os.path.join(lang_dir, f"{lang}.json")
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data[key] = translation
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Added {key} to {lang}.json")
        else:
            print(f"File {file_path} does not exist")
