import json
import os

# Directory containing the language files
lang_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "p3/libs/lang/")

# Translations dictionary: key -> {lang_code: translation}
translations = {
"app_page_rate_submit": {
    "am": "አስገባ",
    "ar": "إرسال",
    "az": "Göndər",
    "bg": "Изпращане",
    "bn": "জমা দিন",
    "bs": "Pošalji",
    "cs": "Odeslat",
    "da": "Indsend",
    "de": "Absenden",
    "el": "Υποβολή",
    "es": "Enviar",
    "et": "Esita",
    "fa": "ارسال",
    "fi": "Lähetä",
    "fr": "Envoyer",
    "ga": "Cuir isteach",
    "he": "שליחה",
    "hi": "सबमिट करें",
    "hr": "Pošalji",
    "hu": "Beküldés",
    "hy": "Ուղարկել",
    "id": "Kirim",
    "is": "Senda inn",
    "it": "Invia",
    "ja": "送信",
    "ka": "გაგზავნა",
    "km": "ដាក់ស្នើ",
    "ko": "제출",
    "lo": "ສົ່ງ",
    "lt": "Pateikti",
    "lv": "Iesniegt",
    "mn": "Илгээх",
    "ms": "Hantar",
    "my": "ပေးပို့ရန်",
    "nb": "Send inn",
    "ne": "पेश गर्नुहोस्",
    "nl": "Indienen",
    "pl": "Prześlij",
    "pt": "Enviar",
    "ro": "Trimite",
    "ru": "Отправить",
    "sk": "Odoslať",
    "sl": "Pošlji",
    "sq": "Dërgo",
    "sr": "Пошаљи",
    "sv": "Skicka",
    "sw": "Wasilisha",
    "ta": "சமர்ப்பி",
    "tg": "Фиристодан",
    "th": "ส่ง",
    "tl": "Isumite",
    "tr": "Gönder",
    "uk": "Надіслати",
    "ur": "جمع کرائیں",
    "uz": "Yuborish",
    "vi": "Gửi",
    "zh": "提交"
},

"app_page_rate_success_title": {
    "am": "ደረጃው ተልኳል",
    "ar": "تم إرسال التقييم",
    "az": "Qiymətləndirmə Göndərildi",
    "bg": "Оценката е изпратена",
    "bn": "রেটিং জমা দেওয়া হয়েছে",
    "bs": "Ocjena je poslana",
    "cs": "Hodnocení odesláno",
    "da": "Bedømmelse indsendt",
    "de": "Bewertung übermittelt",
    "el": "Η αξιολόγηση υποβλήθηκε",
    "es": "Calificación enviada",
    "et": "Hinnang esitatud",
    "fa": "امتیاز ارسال شد",
    "fi": "Arvio lähetetty",
    "fr": "Évaluation envoyée",
    "ga": "Rátáil curtha isteach",
    "he": "הדירוג נשלח",
    "hi": "रेटिंग सबमिट हो गई",
    "hr": "Ocjena je poslana",
    "hu": "Értékelés beküldve",
    "hy": "Գնահատականն ուղարկվել է",
    "id": "Penilaian Terkirim",
    "is": "Einkunn send inn",
    "it": "Valutazione inviata",
    "ja": "評価を送信しました",
    "ka": "შეფასება გაგზავნილია",
    "km": "បានដាក់ស្នើការវាយតម្លៃ",
    "ko": "평가 제출 완료",
    "lo": "ສົ່ງຄະແນນແລ້ວ",
    "lt": "Įvertinimas pateiktas",
    "lv": "Vērtējums iesniegts",
    "mn": "Үнэлгээ илгээгдлээ",
    "ms": "Penilaian Dihantar",
    "my": "အဆင့်သတ်မှတ်ချက် ပေးပို့ပြီးပါပြီ",
    "nb": "Vurdering sendt inn",
    "ne": "मूल्याङ्कन पेश गरियो",
    "nl": "Beoordeling ingediend",
    "pl": "Ocena przesłana",
    "pt": "Avaliação Enviada",
    "ro": "Evaluare trimisă",
    "ru": "Оценка отправлена",
    "sk": "Hodnotenie odoslané",
    "sl": "Ocena poslana",
    "sq": "Vlerësimi u dërgua",
    "sr": "Оцена је послата",
    "sv": "Betyg inskickat",
    "sw": "Tathmini Imewasilishwa",
    "ta": "மதிப்பீடு சமர்ப்பிக்கப்பட்டது",
    "tg": "Арзёбӣ фиристода шуд",
    "th": "ส่งคะแนนแล้ว",
    "tl": "Naisumite ang Rating",
    "tr": "Değerlendirme Gönderildi",
    "uk": "Оцінку надіслано",
    "ur": "درجہ بندی جمع کرا دی گئی",
    "uz": "Baho Yuborildi",
    "vi": "Đã gửi đánh giá",
    "zh": "评分已提交"
},

"app_page_rate_success_message": {
    "am": "እናመሰግናለን! ደረጃዎ ወደ ODRS ተልኳል።",
    "ar": "شكرًا لك! تم إرسال تقييمك إلى ODRS.",
    "az": "Təşəkkür edirik! Qiymətləndirməniz ODRS-ə göndərildi.",
    "bg": "Благодарим! Вашата оценка беше изпратена до ODRS.",
    "bn": "ধন্যবাদ! আপনার রেটিং ODRS-এ জমা দেওয়া হয়েছে।",
    "bs": "Hvala! Vaša ocjena je poslana na ODRS.",
    "cs": "Děkujeme! Vaše hodnocení bylo odesláno do ODRS.",
    "da": "Tak! Din bedømmelse blev indsendt til ODRS.",
    "de": "Vielen Dank! Deine Bewertung wurde an ODRS übermittelt.",
    "el": "Ευχαριστούμε! Η αξιολόγησή σας υποβλήθηκε στο ODRS.",
    "es": "¡Gracias! Tu calificación fue enviada a ODRS.",
    "et": "Aitäh! Teie hinnang esitati ODRS-i.",
    "fa": "متشکریم! امتیاز شما به ODRS ارسال شد.",
    "fi": "Kiitos! Arviosi lähetettiin ODRS:ään.",
    "fr": "Merci ! Votre évaluation a été envoyée à ODRS.",
    "ga": "Go raibh maith agat! Cuireadh do rátáil isteach chuig ODRS.",
    "he": "תודה! הדירוג שלכם נשלח אל ODRS.",
    "hi": "धन्यवाद! आपकी रेटिंग ODRS पर सबमिट कर दी गई।",
    "hr": "Hvala! Vaša ocjena je poslana na ODRS.",
    "hu": "Köszönjük! Az értékelésed elküldésre került az ODRS-nek.",
    "hy": "Շնորհակալություն։ Ձեր գնահատականն ուղարկվել է ODRS։",
    "id": "Terima kasih! Penilaian Anda telah dikirim ke ODRS.",
    "is": "Takk! Einkunnin þín var send til ODRS.",
    "it": "Grazie! La tua valutazione è stata inviata a ODRS.",
    "ja": "ありがとうございます！評価が ODRS に送信されました。",
    "ka": "გმადლობთ! თქვენი შეფასება ODRS-ში გაიგზავნა.",
    "km": "សូមអរគុណ! ការវាយតម្លៃរបស់អ្នកត្រូវបានដាក់ស្នើទៅ ODRS។",
    "ko": "감사합니다! 평가가 ODRS에 제출되었습니다.",
    "lo": "ຂອບໃຈ! ຄະແນນຂອງທ່ານຖືກສົ່ງໄປຫາ ODRS ແລ້ວ.",
    "lt": "Ačiū! Jūsų įvertinimas pateiktas ODRS.",
    "lv": "Paldies! Jūsu vērtējums tika iesniegts ODRS.",
    "mn": "Баярлалаа! Таны үнэлгээг ODRS руу илгээлээ.",
    "ms": "Terima kasih! Penilaian anda telah dihantar ke ODRS.",
    "my": "ကျေးဇူးတင်ပါသည်! သင့်အဆင့်သတ်မှတ်ချက်ကို ODRS သို့ ပေးပို့ပြီးပါပြီ။",
    "nb": "Takk! Vurderingen din ble sendt inn til ODRS.",
    "ne": "धन्यवाद! तपाईंको मूल्याङ्कन ODRS मा पेश गरियो।",
    "nl": "Bedankt! Je beoordeling is ingediend bij ODRS.",
    "pl": "Dziękujemy! Twoja ocena została przesłana do ODRS.",
    "pt": "Obrigado! Sua avaliação foi enviada ao ODRS.",
    "ro": "Mulțumim! Evaluarea ta a fost trimisă la ODRS.",
    "ru": "Спасибо! Ваша оценка была отправлена в ODRS.",
    "sk": "Ďakujeme! Vaše hodnotenie bolo odoslané do ODRS.",
    "sl": "Hvala! Vaša ocena je bila poslana v ODRS.",
    "sq": "Faleminderit! Vlerësimi juaj u dërgua në ODRS.",
    "sr": "Хвала! Ваша оцена је послата на ODRS.",
    "sv": "Tack! Ditt betyg skickades till ODRS.",
    "sw": "Asante! Tathmini yako imewasilishwa kwa ODRS.",
    "ta": "நன்றி! உங்கள் மதிப்பீடு ODRS-க்கு சமர்ப்பிக்கப்பட்டது.",
    "tg": "Ташаккур! Арзёбии шумо ба ODRS фиристода шуд.",
    "th": "ขอบคุณ! คะแนนของคุณถูกส่งไปยัง ODRS แล้ว",
    "tl": "Salamat! Naisumite ang iyong rating sa ODRS.",
    "tr": "Teşekkürler! Değerlendirmeniz ODRS'ye gönderildi.",
    "uk": "Дякуємо! Вашу оцінку надіслано до ODRS.",
    "ur": "شکریہ! آپ کی درجہ بندی ODRS کو جمع کرا دی گئی۔",
    "uz": "Rahmat! Bahoyingiz ODRS'ga yuborildi.",
    "vi": "Cảm ơn bạn! Đánh giá của bạn đã được gửi tới ODRS.",
    "zh": "谢谢！你的评分已提交至 ODRS。"
},

"app_page_rate_failed_title": {
    "am": "ደረጃው አልተላከም",
    "ar": "فشل إرسال التقييم",
    "az": "Qiymətləndirmə Göndərilmədi",
    "bg": "Неуспешно изпращане на оценката",
    "bn": "রেটিং জমা দেওয়া ব্যর্থ হয়েছে",
    "bs": "Slanje ocjene nije uspjelo",
    "cs": "Odeslání hodnocení selhalo",
    "da": "Bedømmelsen mislykkedes",
    "de": "Bewertung fehlgeschlagen",
    "el": "Η αξιολόγηση απέτυχε",
    "es": "Error al enviar la calificación",
    "et": "Hinnangu saatmine ebaõnnestus",
    "fa": "ارسال امتیاز ناموفق بود",
    "fi": "Arvion lähetys epäonnistui",
    "fr": "Échec de l'évaluation",
    "ga": "Theip ar an rátáil",
    "he": "שליחת הדירוג נכשלה",
    "hi": "रेटिंग विफल रही",
    "hr": "Slanje ocjene nije uspjelo",
    "hu": "Az értékelés sikertelen",
    "hy": "Գնահատման ուղարկումը ձախողվեց",
    "id": "Penilaian Gagal",
    "is": "Einkunn mistókst",
    "it": "Valutazione non riuscita",
    "ja": "評価の送信に失敗しました",
    "ka": "შეფასება ვერ გაიგზავნა",
    "km": "ការវាយតម្លៃបានបរាជ័យ",
    "ko": "평가 실패",
    "lo": "ການໃຫ້ຄະແນນລົ້ມເຫຼວ",
    "lt": "Įvertinimas nepavyko",
    "lv": "Vērtēšana neizdevās",
    "mn": "Үнэлгээ амжилтгүй боллоо",
    "ms": "Penilaian Gagal",
    "my": "အဆင့်သတ်မှတ်ခြင်း မအောင်မြင်ပါ",
    "nb": "Vurderingen mislyktes",
    "ne": "मूल्याङ्कन असफल भयो",
    "nl": "Beoordeling mislukt",
    "pl": "Nie udało się przesłać oceny",
    "pt": "Falha na Avaliação",
    "ro": "Evaluarea a eșuat",
    "ru": "Не удалось отправить оценку",
    "sk": "Hodnotenie zlyhalo",
    "sl": "Ocenjevanje ni uspelo",
    "sq": "Vlerësimi dështoi",
    "sr": "Слање оцене није успело",
    "sv": "Betygsättningen misslyckades",
    "sw": "Tathmini Imeshindikana",
    "ta": "மதிப்பீடு தோல்வியடைந்தது",
    "tg": "Арзёбӣ ноком шуд",
    "th": "การให้คะแนนล้มเหลว",
    "tl": "Nabigo ang Rating",
    "tr": "Değerlendirme Başarısız",
    "uk": "Не вдалося надіслати оцінку",
    "ur": "درجہ بندی ناکام ہو گئی",
    "uz": "Baholash Muvaffaqiyatsiz",
    "vi": "Đánh giá thất bại",
    "zh": "评分失败"
},

"app_page_rate_failed_message": {
    "am": "ደረጃውን መላክ አልተቻለም። እባክዎ ቆይተው እንደገና ይሞክሩ።",
    "ar": "تعذر إرسال التقييم. يرجى المحاولة مرة أخرى لاحقًا.",
    "az": "Qiymətləndirməni göndərmək mümkün olmadı. Daha sonra yenidən cəhd edin.",
    "bg": "Оценката не можа да бъде изпратена. Моля, опитайте отново по-късно.",
    "bn": "রেটিং জমা দেওয়া যায়নি। অনুগ্রহ করে পরে আবার চেষ্টা করুন।",
    "bs": "Nije moguće poslati ocjenu. Pokušajte ponovo kasnije.",
    "cs": "Hodnocení se nepodařilo odeslat. Zkuste to prosím později.",
    "da": "Bedømmelsen kunne ikke indsendes. Prøv igen senere.",
    "de": "Die Bewertung konnte nicht übermittelt werden. Bitte versuche es später erneut.",
    "el": "Δεν ήταν δυνατή η υποβολή της αξιολόγησης. Δοκιμάστε ξανά αργότερα.",
    "es": "No se pudo enviar la calificación. Inténtalo de nuevo más tarde.",
    "et": "Hinnangut ei õnnestunud esitada. Proovige hiljem uuesti.",
    "fa": "امتیاز ارسال نشد. لطفاً بعداً دوباره تلاش کنید.",
    "fi": "Arviota ei voitu lähettää. Yritä myöhemmin uudelleen.",
    "fr": "Impossible d'envoyer l'évaluation. Veuillez réessayer plus tard.",
    "ga": "Níorbh fhéidir an rátáil a chur isteach. Bain triail eile as ar ball.",
    "he": "לא ניתן היה לשלוח את הדירוג. נסו שוב מאוחר יותר.",
    "hi": "रेटिंग सबमिट नहीं की जा सकी। कृपया बाद में फिर से प्रयास करें।",
    "hr": "Nije moguće poslati ocjenu. Pokušajte ponovno kasnije.",
    "hu": "Nem sikerült beküldeni az értékelést. Próbáld újra később.",
    "hy": "Չհաջողվեց ուղարկել գնահատականը։ Խնդրում ենք ավելի ուշ կրկին փորձել։",
    "id": "Tidak dapat mengirim penilaian. Silakan coba lagi nanti.",
    "is": "Ekki tókst að senda einkunnina inn. Reyndu aftur síðar.",
    "it": "Impossibile inviare la valutazione. Riprova più tardi.",
    "ja": "評価を送信できませんでした。後でもう一度お試しください。",
    "ka": "შეფასების გაგზავნა ვერ მოხერხდა. გთხოვთ, მოგვიანებით სცადოთ.",
    "km": "មិនអាចដាក់ស្នើការវាយតម្លៃបានទេ។ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។",
    "ko": "평가를 제출할 수 없습니다. 나중에 다시 시도하세요.",
    "lo": "ບໍ່ສາມາດສົ່ງຄະແນນໄດ້. ກະລຸນາລອງໃໝ່ພາຍຫຼັງ.",
    "lt": "Nepavyko pateikti įvertinimo. Bandykite dar kartą vėliau.",
    "lv": "Neizdevās iesniegt vērtējumu. Lūdzu, mēģiniet vēlreiz vēlāk.",
    "mn": "Үнэлгээг илгээж чадсангүй. Дараа дахин оролдоно уу.",
    "ms": "Tidak dapat menghantar penilaian. Sila cuba lagi kemudian.",
    "my": "အဆင့်သတ်မှတ်ချက်ကို ပေးပို့၍ မရပါ။ ကျေးဇူးပြု၍ နောက်မှ ထပ်မံကြိုးစားပါ။",
    "nb": "Kunne ikke sende inn vurderingen. Prøv igjen senere.",
    "ne": "मूल्याङ्कन पेश गर्न सकिएन। कृपया पछि फेरि प्रयास गर्नुहोस्।",
    "nl": "De beoordeling kon niet worden ingediend. Probeer het later opnieuw.",
    "pl": "Nie udało się przesłać oceny. Spróbuj ponownie później.",
    "pt": "Não foi possível enviar a avaliação. Tente novamente mais tarde.",
    "ro": "Evaluarea nu a putut fi trimisă. Încearcă din nou mai târziu.",
    "ru": "Не удалось отправить оценку. Повторите попытку позже.",
    "sk": "Hodnotenie sa nepodarilo odoslať. Skúste to znova neskôr.",
    "sl": "Ocene ni bilo mogoče poslati. Poskusite znova pozneje.",
    "sq": "Nuk u arrit të dërgohej vlerësimi. Provo përsëri më vonë.",
    "sr": "Није могуће послати оцену. Покушајте поново касније.",
    "sv": "Det gick inte att skicka in betyget. Försök igen senare.",
    "sw": "Haikuwezekana kuwasilisha tathmini. Tafadhali jaribu tena baadaye.",
    "ta": "மதிப்பீட்டைச் சமர்ப்பிக்க முடியவில்லை. பின்னர் மீண்டும் முயற்சிக்கவும்.",
    "tg": "Арзёбиро фиристодан имкон нашуд. Лутфан баъдтар аз нав кӯшиш кунед.",
    "th": "ไม่สามารถส่งคะแนนได้ โปรดลองอีกครั้งในภายหลัง",
    "tl": "Hindi maisumite ang rating. Pakisubukan muli mamaya.",
    "tr": "Değerlendirme gönderilemedi. Lütfen daha sonra tekrar deneyin.",
    "uk": "Не вдалося надіслати оцінку. Спробуйте ще раз пізніше.",
    "ur": "درجہ بندی جمع نہیں کرائی جا سکی۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
    "uz": "Bahoni yuborib bo‘lmadi. Keyinroq qayta urinib ko‘ring.",
    "vi": "Không thể gửi đánh giá. Vui lòng thử lại sau.",
    "zh": "无法提交评分，请稍后重试。"
},
}

# Skip 'en' since it's already added
for key, lang_translations in translations.items():
    for lang, translation in lang_translations.items():
        file_path = os.path.join(lang_dir, f"{lang}.json")
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data[key] = translation
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Added {key} to {lang}.json")
        else:
            print(f"File {file_path} does not exist")
