#!/bin/bash
alias_name="linuxtoys"
alias_command="/usr/bin/linuxtoys.sh"
    
# Check if the alias already exists
if ! alias "$alias_name" 2>/dev/null; then
    # If it doesn't exist, add it to the appropriate file
    echo "alias $alias_name='$alias_command'" >> /etc/bash.bashrc
    echo "Alias '$alias_name' created."
else
    echo "Alias '$alias_name' already exists."
fi
exit 0
    
